backend/home/api/v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from home.api.v1.viewsets import (
    SignupViewSet,
    LoginViewSet,
)

router = DefaultRouter()
router.register("signup", SignupViewSet, basename="signup")
router.register("login", LoginViewSet, basename="login")

urlpatterns = [
    path("", include(router.urls)),
]

backend/home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path("", home, name="home"),
]

backend/modules/urls.py
from pathlib import Path
from django.conf import settings
from django.urls import path, include


urlpatterns = []


# BE CAREFUL! Do not remove or change this code snippet, this is needed to get
# Crowdbotics' official modules working properly.

try:
    modules_dir = f"{settings.BASE_DIR}/modules/"
    urls = Path(modules_dir).rglob('urls.py')
    for url in urls:
        module_name, _ = url.as_posix().split('/')[-2:]
        if not module_name == "modules":
            urlpatterns += [
                path(f"{module_name}/", include(f"modules.{module_name}.urls"))  # noqa
            ]
except (ImportError, IndexError):
    pass

backend/users/urls.py
from django.urls import path

from users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

backend/yuvicraft_mobile_26125/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
from allauth.account.views import confirm_email
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

urlpatterns = [
    path("", include("home.urls")),
    path("accounts/", include("allauth.urls")),
    path("modules/", include("modules.urls")),
    path("api/v1/", include("home.api.v1.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("rest-auth/", include("rest_auth.urls")),
    # Override email confirm to use allauth's HTML view instead of rest_auth's API view
    path("rest-auth/registration/account-confirm-email/<str:key>/", confirm_email),
    path("rest-auth/registration/", include("rest_auth.registration.urls")),
]

admin.site.site_header = "Yuvicraft_mobile"
admin.site.site_title = "Yuvicraft_mobile Admin Portal"
admin.site.index_title = "Yuvicraft_mobile Admin"

# swagger
api_info = openapi.Info(
    title="Yuvicraft_mobile API",
    default_version="v1",
    description="API documentation for Yuvicraft_mobile App",
)

schema_view = get_schema_view(
    api_info,
    public=True,
    permission_classes=(permissions.IsAuthenticated,),
)

urlpatterns += [
    path("api-docs/", schema_view.with_ui("swagger", cache_timeout=0), name="api_docs")
]


urlpatterns += [path("", TemplateView.as_view(template_name='index.html'))]
urlpatterns += [re_path(r"^(?:.*)/?$",
                TemplateView.as_view(template_name='index.html'))]

backend/home/models.py
from django.db import models

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    # WARNING!
    """
    Some officially supported features of Crowdbotics Dashboard depend on the initial
    state of this User model (Such as the creation of superusers using the CLI
    or password reset in the dashboard). Changing, extending, or modifying this model
    may lead to unexpected bugs and or behaviors in the automated flows provided
    by Crowdbotics. Change it at your own risk.


    This model represents the User instance of the system, login system and
    everything that relates with an `User` is represented by this model.
    """

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, null=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

backend/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

backend/home/views.py
from django.shortcuts import render


def home(request):
    packages = [
	{'name':'django-allauth', 'url': 'https://pypi.org/project/django-allauth/0.38.0/'},
	{'name':'django-bootstrap4', 'url': 'https://pypi.org/project/django-bootstrap4/0.0.7/'},
	{'name':'djangorestframework', 'url': 'https://pypi.org/project/djangorestframework/3.9.0/'},
    ]
    context = {
        'packages': packages
    }
    return render(request, 'home/index.html', context)

backend/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

backend/home/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/themes/tim.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href={% static 'css/main.css' %} >

    <title>{{ customtext.title|striptags }}</title>
  </head>
  <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand editable" data-remote="{{ customtext.api }}" data-field="{{ customtext.field }}" href="/">
              {{ customtext.title|safe }}
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% if user.is_superuser %}
            <span class="btn btn-success top-right" id="editor" title="Change to inline editor">Edit</span>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script>
        $('#editor').on('click', function (e) {
            if (e.target.innerText === 'Edit'){
                e.target.innerText = 'Cancel';
                var editor = new MediumEditor('.editable');
                editor.subscribe('editableBlur', function (event, editable) {
                    var url = editable.dataset.remote;
                    var field = editable.dataset.field;
                    var data = {};
                    data[field] = editable.innerHTML;
                    api_call(url, data);
                });
            } else {
                e.target.innerText = 'Edit';
                window._mediumEditors.forEach(function (editor) {
                    if (editor)
                        editor.destroy();
                })
            }
        });

        function api_call(url, data, method='PATCH'){
            $.ajax({
                type: method,
                url: url,
                data: data,
                dataType: 'json',
                headers: {
                    'X-CSRFToken': $.cookie('csrftoken')
                },
                success: function (response) {
                    toastr.success('Update Successful')
                },
                error: function (response) {
                    toastr.error('Update Unsuccessful')
                }
            });
        }
        toastr.options = {
          "positionClass": "toast-bottom-right",
          "fadeIn": 300,
          "fadeOut": 800,
          "timeOut": 2000,
          "extendedTimeOut": 1000
        }
    </script>
  </body>
</html>

backend/home/templates/home/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block content %}
    <div class="jumbotron mt-5 editable" data-remote="{{ homepage.api }}" data-field="{{ homepage.field }}">
      {{ homepage.body|safe }}
    </div>
    <div class="row mt-0 mb-5">
        {% for package in packages %}
            <div class="col-md-4 mt-5">
                <div class="card">
                  <div class="card-body text-center">
                    <a class="card-title" href="{{package.url}}">{{package.name}}</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="top-140-pad">
        <div class="sticky pull-right">
            <div>
              <a href="https://www.crowdbotics.com/?ref=badge+{{customtext.title}}">
                  <span class="badge badge-success pull-right">
                      <div id="image" style="display:inline;">
                        <img class="img-fluid pencil" src="{% static 'img/slack-app-pencil.png' %}" alt="Built with software packages from crowdbotics.com" height="30" width="30">
                          </div>
                      <div id="texts" style="display:inline; margin-left: 4px;">
                        Made with Crowdbotics.com
                      </div>
                  </span>
              </a>
            </div>
        </div>
    </div>
{% endblock %}

backend/home/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

backend/home/templates/users/user_form.html
{% extends "base.html" %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}